trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  keyvault: 'myvault12345'
  secretname: 'dbpass'

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'keyvaultconnection'
    KeyVaultName: '$(keyvault)'
    SecretsFilter: '$(secretname)'
  name: FetchSecrets

- script: |
    echo "##vso[task.setvariable variable=dbPassword;issecret=true]$(dbpass)"
  displayName: 'Set Secret Variable'
